"""initial schema (11 tables)

Revision ID: 5354a9ed7741
Revises: 
Create Date: 2026-08-13 00:25:53.861037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5354a9ed7741'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anchors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_health',
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success_rate_24h', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_latency_ms_24h', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('error_count_24h', sa.Integer(), nullable=False),
    sa.Column('success_count_24h', sa.Integer(), nullable=False),
    sa.Column('sustained_qps', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_anchors', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('platform')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('unionid', sa.String(length=64), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('platform_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('anchor_id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_user_id', sa.String(length=128), nullable=False),
    sa.Column('room_id', sa.String(length=128), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('last_status', sa.String(length=16), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_live_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adapter_version', sa.String(length=32), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('polling_tier', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['anchors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_user_id', name='uq_pa_platform_user')
    )
    op.create_index('idx_pa_anchor', 'platform_accounts', ['anchor_id'], unique=False)
    op.create_index('idx_pa_due', 'platform_accounts', ['platform', 'is_disabled', 'last_checked_at'], unique=False, postgresql_where='is_disabled = false')
    op.create_index('idx_pa_tier', 'platform_accounts', ['platform', 'polling_tier', 'is_disabled'], unique=False, postgresql_where='is_disabled = false')
    op.create_table('wechat_subscription_grants',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('granted_count', sa.Integer(), nullable=False, comment='用户主动 accept 次数(可累积储备,ADR-002)'),
    sa.Column('consumed_count', sa.Integer(), nullable=False),
    sa.Column('last_granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_send_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_send_error', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'template_id', name='uq_grant_user_template')
    )
    op.create_table('live_sessions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('platform_account_id', sa.BigInteger(), nullable=False),
    sa.Column('anchor_id', sa.BigInteger(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('cover', sa.Text(), nullable=True),
    sa.Column('viewer_count', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['anchors.id'], ),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_anchor_started', 'live_sessions', ['anchor_id', 'started_at'], unique=False)
    op.create_index('idx_session_pa_open', 'live_sessions', ['platform_account_id'], unique=False, postgresql_where="state = 'OPEN'")
    op.create_index('uniq_open_session_per_pa', 'live_sessions', ['platform_account_id'], unique=True, postgresql_where="state = 'OPEN'")
    op.create_table('probe_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('platform_account_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pr_pa_started', 'probe_runs', ['platform_account_id', 'started_at'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('anchor_id', sa.BigInteger(), nullable=False),
    sa.Column('platform_account_id', sa.BigInteger(), nullable=False),
    sa.Column('notify_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('silent_start', sa.Time(), nullable=True),
    sa.Column('silent_end', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['anchors.id'], ),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'platform_account_id', name='uq_sub_user_pa')
    )
    op.create_index('idx_subs_anchor', 'user_subscriptions', ['anchor_id'], unique=False)
    op.create_index('idx_subs_pa', 'user_subscriptions', ['platform_account_id'], unique=False)
    op.create_index('idx_subs_user', 'user_subscriptions', ['user_id'], unique=False)
    op.create_table('live_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('platform_account_id', sa.BigInteger(), nullable=False),
    sa.Column('anchor_id', sa.BigInteger(), nullable=False),
    sa.Column('live_session_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['anchors.id'], ),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_pa_detected', 'live_events', ['platform_account_id', 'detected_at'], unique=False)
    op.create_index('idx_events_session', 'live_events', ['live_session_id'], unique=False)
    op.create_table('notification_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('live_event_id', sa.BigInteger(), nullable=False),
    sa.Column('live_session_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('anchor_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['anchor_id'], ['anchors.id'], ),
    sa.ForeignKeyConstraint(['live_event_id'], ['live_events.id'], ),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('live_event_id', 'user_id', name='uq_nj_event_user')
    )
    op.create_index('idx_nj_state', 'notification_jobs', ['state', 'created_at'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('notification_job_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('live_session_id', sa.BigInteger(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ),
    sa.ForeignKeyConstraint(['notification_job_id'], ['notification_jobs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'live_session_id', 'channel', name='uq_nd_user_session_channel')
    )
    op.create_index('idx_nd_state', 'notification_deliveries', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_nd_state', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index('idx_nj_state', table_name='notification_jobs')
    op.drop_table('notification_jobs')
    op.drop_index('idx_events_session', table_name='live_events')
    op.drop_index('idx_events_pa_detected', table_name='live_events')
    op.drop_table('live_events')
    op.drop_index('idx_subs_user', table_name='user_subscriptions')
    op.drop_index('idx_subs_pa', table_name='user_subscriptions')
    op.drop_index('idx_subs_anchor', table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index('idx_pr_pa_started', table_name='probe_runs')
    op.drop_table('probe_runs')
    op.drop_index('uniq_open_session_per_pa', table_name='live_sessions', postgresql_where="state = 'OPEN'")
    op.drop_index('idx_session_pa_open', table_name='live_sessions', postgresql_where="state = 'OPEN'")
    op.drop_index('idx_session_anchor_started', table_name='live_sessions')
    op.drop_table('live_sessions')
    op.drop_table('wechat_subscription_grants')
    op.drop_index('idx_pa_tier', table_name='platform_accounts', postgresql_where='is_disabled = false')
    op.drop_index('idx_pa_due', table_name='platform_accounts', postgresql_where='is_disabled = false')
    op.drop_index('idx_pa_anchor', table_name='platform_accounts')
    op.drop_table('platform_accounts')
    op.drop_table('users')
    op.drop_table('platform_health')
    op.drop_table('anchors')
    # ### end Alembic commands ###
