"""add live_sessions.started_at_source

Revision ID: e98c1011d830
Revises: c23b5e229894
Create Date: 2026-08-14 13:00:22.216141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98c1011d830'
down_revision: Union[str, Sequence[str], None] = 'c23b5e229894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_sessions', sa.Column('started_at_source', sa.String(length=16), server_default='probe', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_sessions', 'started_at_source')
    # ### end Alembic commands ###
